version: '3.8'

services:
  test-radar:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./reports:/app/reports
      - ./test_samples:/app/test_samples
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    command: python3 run_analysis.py
    networks:
      - test-radar-net

networks:
  test-radar-net:
    driver: bridge
